### ISSUE TITLE
unsafe use of Sys.command and %s

### ISSUE THREAD

**Issue by edwintorok** [mirage/mirage-fs-unix#15]
There are several problems with the use of `Sys.command`:
  * it is blocking
  * `%s` is used to build the command-line but I don't see any shell escaping, so its quite possible to cause problems if the filename contains spaces, backticks or semicolons (in which case its possible to inject arbitrary commands through filenames)

`Sys.command` could be replaced with something from `Lwt_process`, but looking at its uses it might be better to just replace all uses of `command` with OCaml code:
  * calling `touch %s` to create a file could probably be performed more efficiently and safely by opening and closing the file on OCaml side
  * I'm not sure if the semantics of `destroy` should imply `rm -rf %s`, at least `fat-filesystem` returns an error when the directory is not empty, so perhaps this should just be an `unlink` or `rmdir`, and the comment in `V1.mli` doesn't say it should be recursive

**Comment by hannesm** [comment]
in master, Sys.command has been removed (I believe there should be a new release of mirage-fs-unix..)

**Comment by mor1** [comment]
Idle thought-- could @dsheets `Yorick` from the ocaml/ocaml-travisci-skeleton repo be used to good effect here?  (In which case it might usefully be separately packaged.)

**Comment by dbuenzli** [comment]
> @dsheets Yorick from the ocaml/ocaml-travisci-skeleton repo be used to good effect here?

Please don't.

**Comment by samoht** [comment]
I'll cut a new release, thanks for the ping.

**Comment by samoht** [comment]
See https://github.com/ocaml/opam-repository/pull/4528
