### ISSUE TITLE
No unit-tests

### ISSUE THREAD

**Issue by samoht** [mirage/mirage-fs-unix#7]
We should add unit tests, to catch trivial bugs such as the one fixed by #6

**Comment by avsm** [comment]
Modern Travis added in #9 to start this off.

**Comment by hannesm** [comment]
I believe thanks to @yomimono #10 this can be closed!

**Comment by yomimono** [comment]
There are still no tests for `create`, `destroy`, or `format`, sadly.

**Comment by hannesm** [comment]
#12 adds some :D also for listdir, indirectly

**Comment by yomimono** [comment]
Nice! :D

**Comment by samoht** [comment]
We indeed now have unit tests :-)
